name: DevSecOps Pipeline Demo

permissions:
  contents: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run basic tests (placeholder)
        run: |
          source venv/bin/activate
          PYTHONPATH=. pytest tests/

  sast:
    name: Static Analysis (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/default'

  
  dast:
    name: Run ZAP and Save Report
    runs-on: ubuntu-latest
    outputs:
      report-path: ${{ steps.zap.outputs.report-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Flask with Gunicorn
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          nohup gunicorn --bind 0.0.0.0:5000 --no-sendfile --no-server-header app:app &
          sleep 10

      - name: Run ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.6.0
        with:
          target: 'http://localhost:5000'
          fail_action: false
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'

      - name: Copy ZAP report to docs folder
        run: |
          mkdir -p docs
          cp owasp-zap-report.html docs/index.html

      - name: Upload artifact manually
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: shared/zap-report.html